# SPDX-FileCopyrightText: 2022 Serokell <https://serokell.io>
# SPDX-License-Identifier: CC0-1.0

name: hsblst
version: 0
author: Serokell <hi@serokell.io>
github: serokell/hsblst

synopsis: Haskell bindings to BLST
description:
  HsBLST is low-level Haskell bindings and a high-level interface to
  [BLST](https://github.com/supranational/blst) -- a multilingual BLS12-381
  signature library.
category: Cryptography

copyright: 2022 Serokell <https://serokell.io>
license-file: LICENSE
license: MPL-2.0

maintainer:
- Nikolay "Lierdakil" Yakimov <nikolay.yakimov@serokell.io>
tested-with:
  - GHC == 9.0.2
  - GHC == 9.2.7
  - GHC == 9.4.4

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NegativeLiterals
  - NoStarIsType
  - NumDecimals
  - OverloadedLabels
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - RecursiveDo
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - UndecidableSuperClasses
  - ViewPatterns

ghc-options:
  - -Weverything
  - -Wno-missing-exported-signatures
  - -Wno-missing-import-lists
  - -Wno-missed-specialisations
  - -Wno-all-missed-specialisations
  - -Wno-unsafe
  - -Wno-safe
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-implicit-prelude
  - -Wno-prepositive-qualified-module
  - -Wno-inferred-safe-imports
  - -Wno-missing-safe-haskell-mode

when:
  - condition: impl(ghc >= 9.2)
    ghc-options:
      - -Wno-missing-kind-signatures

extra-source-files:
- README.md
- CHANGELOG.md
- c-source/build/**/*.s
- c-source/build/**/*.S
- c-source/src/**/*.c
- c-source/src/**/*.h
- c-source/bindings/*.h
- c-source/LICENSE
- c-source/README.md

dependencies:
  - base >=4.15.1.0 && <4.18
  - memory >=0.16.0 && <0.19

library:
  source-dirs: src
  include-dirs: c-source/bindings
  build-tools: c2hs:c2hs
  dependencies:
    - deepseq ^>=1.4.5.0
  c-sources:
    - c-source/src/server.c
    - c-source/build/assembly.S

tests:
  hsblst-test:
    main:        Main.hs
    source-dirs: test
    build-tools: tasty-discover:tasty-discover

    ghc-options:
    - -Wno-incomplete-patterns
    - -threaded
    - '"-with-rtsopts=-N -A64m -AL256m"'

    when:
      - condition: impl(ghc < 9.4)
        ghc-options:
          - -eventlog

    dependencies:
    - hsblst
    - bytestring >=0.10.12.1 && <0.12
    - hex-text ^>=0.1.0.6
    - tasty ^>=1.4.2.1
    - tasty-hunit ^>=0.10.0.3
    - text ^>=1.2.5.0 || ^>=2.0.1
