# SPDX-FileCopyrightText: 2023 Serokell <https://serokell.io>
# SPDX-License-Identifier: MPL-2.0

root-instances = [{ class = "\\.TestGroup$" }]
roots = [
  "^Main\\.main$",
  "^Crypto\\.BLST\\..*$",
  "^Paths_.*",
]
unused-types = true
